name: 'Auto Code Review'
description: 'Automatically review code changes in pull requests using Claude API'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  github_repository:
    description: 'GitHub repository'
    required: true
  github_pull_request_number:
    description: 'Pull request number'
    required: true
  claude_api_key:
    description: 'Claude API key'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Start Review
      shell: bash
      env:
          GITHUB_TOKEN: ${{ inputs.github_token }}
          CLAUDE_API_KEY: ${{ inputs.claude_api_key }}
      run: |
        python3 client.py \
          --github_token ${{ inputs.github_token }} \
          --repository ${{ inputs.github_repository }} \
          --pull_request_number ${{ inputs.github_pull_request_number }}