name: 'Auto Code Review'
description: 'Automatically review code changes in pull requests using Ollama API'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  repository:
    description: 'GitHub repository'
    required: true
  pull_request_number:
    description: 'Pull request number'
    required: true
  local_ai_key:
    description: 'Ollma API key'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Install dependencies
      shell: bash
      run: |
        uv venv
        uv pip install -r requirements.txt
    - name: Start Review
      shell: bash
      env:
          GITHUB_TOKEN: ${{ inputs.github_token }}
          LOCAL_AI_KEY: ${{ inputs.local_ai_key }}
      run: |
        python3 client.py \
          --github_token ${{ inputs.github_token }} \
          --repository ${{ inputs.repository }} \
          --pull_request_number ${{ inputs.pull_request_number }}
