name: "Code Review"
on:
  pull_request:
    types: [opened]
    paths-ignore:
      - "*.md"
      - "LICENSE"

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          repository: AnAIAudio/CodeReview
          ref: main
          token: ${{ secrets.PAT_TOKEN }}
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          local_ai_key: ${{ secrets.LOCAL_AI_KEY }}
          repository: ${{ github.repository }}
          pull_request_number: ${{ github.event.pull_request.number }}