name: "Code Review"
on:
  pull_request:
    types: [opened]
    paths-ignore:
      - "*.md"
      - "LICENSE"
jobs:
  review:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: "Code Review by claude"
        uses: localsearch-refine/auto-code-review@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          github_pull_request_number: ${{ github.event.pull_request.number }}
          git_commit_hash: ${{ github.event.pull_request.head.sha }}
